name: Pyinstaller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          pyinstaller_ver: '>=6.15.0'
          spec: 'MyOrganizer.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'MyOrganizer-${{ runner.os }}'
